###############################################################################
# Phase 2: Convert Azure AI Foundry Demo to Private Endpoint Access
#
# This script converts the demo from public access to private endpoint access.
# It enables Azure AI Foundry to be accessed ONLY from the App Service via
# a private endpoint, while disabling public internet access.
#
# Prerequisites:
#   - Phase 1 deployment already completed (scripts/01-deploy-public-access.ps1)
#   - Azure CLI installed (az command available)
#   - Logged in to Azure (az login)
#   - Appropriate Azure permissions (Network Contributor, Cognitive Services Contributor)
#
# Architecture:
#   App Service (VNet Integration) ──▶ Private Endpoint ──▶ Azure AI Foundry
#   └─ Private Subnet                                       (Private Access ONLY)
#
# Usage:
#   pwsh scripts/02-enable-private-access.ps1
#
###############################################################################

$ErrorActionPreference = "Stop"

# ============================================================================
# Helper functions
# ============================================================================

function Log-Step {
    param([string]$Message)
    Write-Host ""
    Write-Host "════════════════════════════════════════════════════════════════"
    Write-Host "▶ $Message"
    Write-Host "════════════════════════════════════════════════════════════════"
}

function Log-Info {
    param([string]$Message)
    Write-Host "  ℹ $Message"
}

function Log-Success {
    param([string]$Message)
    Write-Host "  ✓ $Message"
}

function Log-Warning {
    param([string]$Message)
    Write-Host "  ⚠ $Message"
}

function Log-Error {
    param([string]$Message)
    Write-Host "  ✗ $Message" -ForegroundColor Red
}

function Assert-AzSuccess {
    param([string]$StepDescription)
    if ($LASTEXITCODE -ne 0) {
        Log-Error "$StepDescription failed (exit code: $LASTEXITCODE). Stopping."
        exit 1
    }
}

function Invoke-AzWithRetry {
    param(
        [string]$Description,
        [scriptblock]$Command,
        [int]$MaxRetries = 3,
        [int]$DelaySeconds = 15
    )
    for ($i = 1; $i -le $MaxRetries; $i++) {
        $output = . $Command
        if ($LASTEXITCODE -eq 0) {
            return $output
        }
        $errorText = $output | Out-String
        if ($errorText -match "ResourceGroupNotFound" -and $i -lt $MaxRetries) {
            Log-Warning "Transient ResourceGroupNotFound on '$Description' (attempt $i/$MaxRetries). Retrying in ${DelaySeconds}s..."
            Start-Sleep -Seconds $DelaySeconds
        } else {
            Write-Host $errorText
            return $null
        }
    }
    return $null
}

# ============================================================================
# RANDOM SUFFIX - Read the same suffix generated by Phase 1 to ensure
# resource names match across both deployment scripts.
# ============================================================================

$SuffixFile = Join-Path $PSScriptRoot ".deploy-suffix"
if (-not (Test-Path $SuffixFile)) {
    Log-Error "Suffix file not found at $SuffixFile"
    Write-Host "Please run scripts/01-deploy-public-access.ps1 first."
    exit 1
}
$Suffix = (Get-Content $SuffixFile -Raw).Trim()
Write-Host "Using deployment suffix: $Suffix"

# ============================================================================
# VARIABLES - Must match Phase 1 deployment
# ============================================================================

$ResourceGroup = "rg-foundry-demo-$Suffix"
$Location = "centralus"

# Azure AI Foundry
$FoundryName = "foundry-demo-ai-$Suffix"

# App Service
$AppServiceName = "foundry-demo-app-$Suffix"

# Network
$VnetName = "foundry-demo-vnet-$Suffix"
$AppServiceSubnet = "app-service-subnet"
$FoundrySubnet = "foundry-subnet"

# Private Endpoint
$PrivateEndpointName = "foundry-demo-pe-$Suffix"
$PrivateEndpointConnection = "foundry-demo-connection-$Suffix"

# Private DNS
$PrivateDnsZone = "privatelink.cognitiveservices.azure.com"
$PrivateDnsLink = "foundry-demo-dns-link-$Suffix"

# ============================================================================
# STEP 1: Enable App Service VNet Integration
# ============================================================================

Log-Step "Step 1: Enable App Service VNet Integration"

Log-Info "Adding VNet integration to App Service (subnet: $AppServiceSubnet)..."
az webapp vnet-integration add `
    --name $AppServiceName `
    --resource-group $ResourceGroup `
    --vnet $VnetName `
    --subnet $AppServiceSubnet `
    -ErrorAction SilentlyContinue 2>$null
if ($LASTEXITCODE -ne 0) {
    Log-Warning "VNet integration may already be enabled"
}

Log-Success "App Service VNet Integration enabled"

# ============================================================================
# STEP 2: Disable Private Endpoint Network Policies on Foundry Subnet
# ============================================================================

Log-Step "Step 2: Disable Private Endpoint Network Policies"

Log-Info "Updating subnet policies on $FoundrySubnet..."
Invoke-AzWithRetry -Description "Subnet policy update" -Command {
    az network vnet subnet update `
        --name $FoundrySubnet `
        --resource-group $ResourceGroup `
        --vnet-name $VnetName `
        --private-endpoint-network-policies Disabled 2>&1
} | Out-Null
Assert-AzSuccess "Subnet network policy update"

Log-Success "Private endpoint network policies disabled on $FoundrySubnet"

# ============================================================================
# STEP 3: Create Private Endpoint
# ============================================================================

Log-Step "Step 3: Create Private Endpoint for Foundry Resource"

$PeExists = Invoke-AzWithRetry -Description "PE check" -Command {
    az network private-endpoint show --name $PrivateEndpointName --resource-group $ResourceGroup --query name -o tsv 2>&1
}
if ($LASTEXITCODE -eq 0 -and $PeExists) {
    Log-Warning "Private endpoint '$PrivateEndpointName' already exists. Skipping creation."
} else {
    Log-Info "Retrieving Foundry resource ID..."
    $FoundryId = Invoke-AzWithRetry -Description "Foundry ID lookup" -Command {
        az cognitiveservices account show --name $FoundryName --resource-group $ResourceGroup --query id -o tsv 2>&1
    }
    if (-not $FoundryId) {
        Log-Error "Could not retrieve Foundry resource ID after retries."
        exit 1
    }

    Log-Info "Creating private endpoint..."
    Invoke-AzWithRetry -Description "PE creation" -Command {
        az network private-endpoint create `
            --name $PrivateEndpointName `
            --resource-group $ResourceGroup `
            --vnet-name $VnetName `
            --subnet $FoundrySubnet `
            --private-connection-resource-id $FoundryId `
            --group-id account `
            --connection-name $PrivateEndpointConnection 2>&1
    } | Out-Null
    Assert-AzSuccess "Private endpoint creation"

    Log-Success "Private endpoint created"
}

# ============================================================================
# STEP 4: Create Private DNS Zone
# ============================================================================

Log-Step "Step 4: Create Private DNS Zone"

$DnsZoneExists = Invoke-AzWithRetry -Description "DNS zone check" -Command {
    az network private-dns zone show --resource-group $ResourceGroup --name $PrivateDnsZone --query name -o tsv 2>&1
}
if ($LASTEXITCODE -eq 0 -and $DnsZoneExists) {
    Log-Warning "Private DNS zone '$PrivateDnsZone' already exists. Skipping creation."
} else {
    Log-Info "Creating private DNS zone..."
    Invoke-AzWithRetry -Description "DNS zone creation" -Command {
        az network private-dns zone create --resource-group $ResourceGroup --name $PrivateDnsZone 2>&1
    } | Out-Null
    Assert-AzSuccess "Private DNS zone creation"

    Log-Success "Private DNS zone created"
}

# ============================================================================
# STEP 5: Link Private DNS Zone to VNet
# ============================================================================

Log-Step "Step 5: Link Private DNS Zone to VNet"

$DnsLinkExists = Invoke-AzWithRetry -Description "DNS link check" -Command {
    az network private-dns link vnet show --resource-group $ResourceGroup --zone-name $PrivateDnsZone --name $PrivateDnsLink --query name -o tsv 2>&1
}
if ($LASTEXITCODE -eq 0 -and $DnsLinkExists) {
    Log-Warning "DNS link '$PrivateDnsLink' already exists. Skipping creation."
} else {
    Log-Info "Linking DNS zone to VNet..."
    Invoke-AzWithRetry -Description "DNS link creation" -Command {
        az network private-dns link vnet create `
            --resource-group $ResourceGroup `
            --zone-name $PrivateDnsZone `
            --name $PrivateDnsLink `
            --virtual-network $VnetName `
            --registration-enabled false 2>&1
    } | Out-Null
    Assert-AzSuccess "DNS zone VNet link creation"

    Log-Success "DNS zone linked to VNet"
}

# ============================================================================
# STEP 6: Create DNS Zone Group for Private Endpoint
# ============================================================================

Log-Step "Step 6: Create DNS Zone Group for Private Endpoint"

$ZoneGroupExists = Invoke-AzWithRetry -Description "Zone group check" -Command {
    az network private-endpoint dns-zone-group show --resource-group $ResourceGroup --endpoint-name $PrivateEndpointName --name "default" --query name -o tsv 2>&1
}
if ($LASTEXITCODE -eq 0 -and $ZoneGroupExists) {
    Log-Warning "DNS zone group already exists. Skipping creation."
} else {
    Log-Info "Creating DNS zone group..."
    Invoke-AzWithRetry -Description "DNS zone group creation" -Command {
        az network private-endpoint dns-zone-group create `
            --resource-group $ResourceGroup `
            --endpoint-name $PrivateEndpointName `
            --name "default" `
            --private-dns-zone $PrivateDnsZone `
            --zone-name "cognitiveservices" 2>&1
    } | Out-Null
    Assert-AzSuccess "DNS zone group creation"

    Log-Success "DNS zone group created (A record will be auto-registered)"
}

# ============================================================================
# STEP 7: Disable Public Network Access on Foundry Resource
# ============================================================================

Log-Step "Step 7: Disable Public Network Access"

Log-Info "Updating Foundry resource to block public access..."
$FoundryId = Invoke-AzWithRetry -Description "Foundry ID for public access" -Command {
    az cognitiveservices account show --name $FoundryName --resource-group $ResourceGroup --query id -o tsv 2>&1
}
if (-not $FoundryId) {
    Log-Error "Could not retrieve Foundry resource ID."
    exit 1
}
$body = '{\"properties\":{\"publicNetworkAccess\":\"Disabled\"}}'
az rest --method PATCH --url "https://management.azure.com${FoundryId}?api-version=2023-05-01" --body $body --headers "Content-Type=application/json" --output none
Assert-AzSuccess "Disable public network access"

Log-Success "Public network access DISABLED on Foundry resource"

# ============================================================================
# VALIDATION & VERIFICATION
# ============================================================================

Log-Step "✓ Phase 2 Deployment Complete (Private Endpoint Access)"

Write-Host ""
Write-Host "════════════════════════════════════════════════════════════════"
Write-Host "VALIDATION COMMANDS"
Write-Host "════════════════════════════════════════════════════════════════"
Write-Host ""
Write-Host "1. Verify private endpoint creation:"
Write-Host "   az network private-endpoint show --name $PrivateEndpointName --resource-group $ResourceGroup"
Write-Host ""
Write-Host "2. Verify private DNS zone group (A record should be registered):"
Write-Host "   az network private-endpoint dns-zone-group show --resource-group $ResourceGroup --endpoint-name $PrivateEndpointName --name default"
Write-Host ""
Write-Host "3. Verify public network access is DISABLED on Foundry:"
Write-Host "   az cognitiveservices account show --name $FoundryName --resource-group $ResourceGroup --query properties.publicNetworkAccess"
Write-Host ""
Write-Host "4. Test diagnostics from App Service (should work - private access via VNet):"
Write-Host "   curl https://${AppServiceName}.azurewebsites.net/api/diagnostics"
Write-Host "   Expected: Status 🟢 (private IP), access through Private Endpoint"
Write-Host ""
Write-Host "5. Test AI API from App Service (should work - private access):"
Write-Host "   curl `"https://${AppServiceName}.azurewebsites.net/api/ask?prompt=Hello%20Private%20Endpoint`""
Write-Host "   Expected: AI response via private connection"
Write-Host ""
Write-Host "6. Verify local access is BLOCKED (from your laptop/local environment):"
Write-Host "   curl `"https://${FoundryName}.cognitiveservices.azure.com/openai/models`" -H `"api-key: <key>`""
Write-Host "   Expected: 403 Forbidden (public access blocked)"
